### ISSUE TITLE
Conversion to GLB

### ISSUE THREAD

**Issue by MuMuJun97** [srama2512/PONI#10]
Hi! Thanks for your Great work! 

I have followed the guidance below for GLB conversion:
https://github.com/srama2512/PONI/blob/main/DATASETS.md: 
- Conversion to GLB can be performed using existing tools like [assimp](https://github.com/assimp/assimp).
`assimp export <OBJ FILE> <GLB PATH>`

when I use the COMMANE: `python download_mp.py --type matterport_mesh -o $PONI_ROOT/data/scene_datasets/mp3d_uncompressed`, I get files like this: `*scans/1LXtFkjw3qL/matterport_mesh.zip`.
Then, I unzip this file and get something like:
```
../scans/1LXtFkjw3qL/matterport_mesh/b94039b4eb8947bdb9ff5719d9173eae$ ls 
b94039b4eb8947bdb9ff5719d9173eae_000.jpg  b94039b4eb8947bdb9ff5719d9173eae_020.jpg  b94039b4eb8947bdb9ff5719d9173eae_083.jpg
......
b94039b4eb8947bdb9ff5719d9173eae.mtl
b94039b4eb8947bdb9ff5719d9173eae.obj
```
Then, I execute the GLB conversion COMMAND:
```
assimp  export  b94039b4eb8947bdb9ff5719d9173eae.obj  1LXtFkjw3qL.glb 
```

When I use the command `python scripts/create_semantic_maps.py`, the `scene_boundaries` at `_ = list(tqdm.tqdm(pool.imap(get_scene_boundaries, inputs), total=len(inputs)))` are successfully generated. 
But I got an error in `_ = list(tqdm.tqdm(pool.imap(_aux_fn, inputs), total=len(inputs)))`:
```
def extract_wall_point_clouds: 
    ......
    scene = trimesh.load(glb_path)

Traceback (most recent call last):
  File "/home/zlin/anaconda3/envs/habitat/lib/python3.8/site-packages/trimesh/exchange/load.py", line 129, in load
    loaded = load_mesh(file_obj,
  File "/home/zlin/anaconda3/envs/habitat/lib/python3.8/site-packages/trimesh/exchange/load.py", line 212, in load_mesh
    results = loader(file_obj,
  File "/home/zlin/anaconda3/envs/habitat/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 401, in load_glb
    kwargs = _read_buffers(header=header,
  File "/home/zlin/anaconda3/envs/habitat/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1360, in _read_buffers
    materials = _parse_materials(
  File "/home/zlin/anaconda3/envs/habitat/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1217, in _parse_materials
    images = _parse_textures(header, views, resolver)
  File "/home/zlin/anaconda3/envs/habitat/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 1185, in _parse_textures
    blob = _uri_to_bytes(uri=img['uri'], resolver=resolver)
  File "/home/zlin/anaconda3/envs/habitat/lib/python3.8/site-packages/trimesh/exchange/gltf.py", line 433, in _uri_to_bytes
    return resolver[uri]
TypeError: 'NoneType' object is not subscriptable
```

So, I would like to inquire whether the above-mentioned GLB conversion procedure is correct?
And, what version of trimesh are you using? 
Hope the above questions are answered, thanks again for your work.

**Comment by srama2512** [comment]
@MuMuJun97 - I tested the code with `trimesh==3.10.2`. So, one point of difference could be that I am using the MP3D files that I got years back before basis compression was made the default habitat MP3D format. I didn't actually do the gltf conversion myself using assimp. I got these instructions (about using assimp) from the MP3D authors. 

This issue may be similar to #3.

**Comment by MuMuJun97** [comment]
@srama2512: Sincerely thank you for your reply! I have converted `*.obj` to `*.glb` file by replacing `assimp` with `trimesh` to solve the above issue:
```python
import trimesh
...
scene = trimesh.load(obj_file)
scene.export(str(glb_file))
...
```

Also, I've found that `max_points=200000` in the 
```
def dense_sampling_trimesh(triangles, density=100.0, max_points=200000):
 ...
```
causes very slow build times. Therefore, I set `max_points = 10000` to speed up the generation process in `ACTIVE_DATASET="mp3d" python scripts/create_semantic_maps.py`. Will this affect the generated data and final performance?

**Comment by srama2512** [comment]
Okay, that's great! Thanks for figuring this out. 

In terms of the number of points, I found 20000 to be generally good. Reducing it may sometimes result in sparser maps with tiny holes. You can play around with it and view the visualized maps to check for issues.

**Comment by MuMuJun97** [comment]
> Okay, that's great! Thanks for figuring this out.
> 
> In terms of the number of points, I found 20000 to be generally good. Reducing it may sometimes result in sparser maps with tiny holes. You can play around with it and view the visualized maps to check for issues.

Thanks for your answer. I'll keep trying and experimenting the performance.
