### ISSUE TITLE
tools/gen_gibson_semantics.sh: line 28: tools/../build/utils/datatool/datatool: No such file or directory

### ISSUE THREAD

**Issue by LIUQI-creat** [srama2512/PONI#12]
Hello, @srama2512 
Thanks for your excellent work!
I want to convert the semantic annotations to habitat format following instructions in [habitat-sim](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#gibson-and-3dscenegraph-datasets), but I encountered this problem: `tools/gen_gibson_semantics.sh: line 24: tools/../build/utils/datatool/datatool: No such file or directory`

I found that there is no utils in `build` and there is a file `utils/datatool` in `src`
How can I resolve this problem ? Thank you very much !

**Comment by dwei-k** [comment]
try to run `python setup.py build --build-datatool`  to generate it

**Comment by LIUQI-creat** [comment]
> 

Thanks for your timely reply! I will follow your advice.  ^_^

**Comment by srama2512** [comment]
@LIUQI-creat - is this issue resolved?

@dwei-k - thanks for suggesting the solution.

**Comment by wbciscodeking** [comment]
I encountered the same problem: tools/gen_gibson_semantics.sh: line 24: tools/../build/utils/datatool/datatool: No such file or directory，but I encountered this problem when I run "python setup.py build --build-datatool"： check.warn(importable)
copying habitat_sim/sensors/noise_models/data/redwood-depth-dist-model.npy -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models/data
running build_ext
error: [Errno 2] No such file or directory: 'build/compile_commands.json'

**Comment by huwem** [comment]
> I encountered the same problem: tools/gen_gibson_semantics.sh: line 24: tools/../build/utils/datatool/datatool: No such file or directory，but I encountered this problem when I run "python setup.py build --build-datatool"： check.warn(importable) copying habitat_sim/sensors/noise_models/data/redwood-depth-dist-model.npy -> build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models/data running build_ext error: [Errno 2] No such file or directory: 'build/compile_commands.json'

Just remove the directory 'build' then try again.

**Comment by wbciscodeking** [comment]
Thanks for your valuable suggestion.I will try it immediately.



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 11, 2025 14:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [srama2512/PONI] tools/gen_gibson_semantics.sh: line 28:tools/../build/utils/datatool/datatool: No such file or directory (Issue #12)


huwem left a comment (srama2512/PONI#12)
  
I encountered the same problem: tools/gen_gibson_semantics.sh: line 24: tools/../build/utils/datatool/datatool: No such file or directory，but I encountered this problem when I run "python setup.py build --build-datatool"： check.warn(importable) copying habitat_sim/sensors/noise_models/data/redwood-depth-dist-model.npy -&gt; build/lib.linux-x86_64-cpython-38/habitat_sim/sensors/noise_models/data running build_ext error: [Errno 2] No such file or directory: 'build/compile_commands.json'
  
Just remove the directory 'build' then try again.
