### ISSUE TITLE
Convert the semantic annotations to habitat format

### ISSUE THREAD

**Issue by leyuan-sun** [srama2512/PONI#14]
ACTIVE_DATASET="gibson" python scripts/create_semantic_maps.py
Number of available scenes: 0
===========> Extracting scene boundaries
0it [00:00, ?it/s]
===========> Extracting point-clouds
0it [00:00, ?it/s]
===========> Extracting semantic maps
0it [00:00, ?it/s]

After I have generated the semantic annotations for Gibson from 3DSceneGraph dataset, I obtained the .ids and .scn files for each scene, and I put all of them in /gibson_semantic folder, then I would like to use create_semantic_maps.py to convert them to habitat format, but I got the aboved msgs. Could you plz take a look? Thanks!

**Comment by leyuan-sun** [comment]
Update: I obtain the .ids .scn ._semantic.ply, and put them in one folder of all scenes, but still got the above msgs when I run that script, could you plz show the structure of files inside of /gibson_semantic folder?

**Comment by leyuan-sun** [comment]
Could you show the dataset folder structure? What are the files inside of gibson_semantic folder, for me, I have scene_name.glb scene_name.navmesh scene_name.ids scene_name.scn scene_name_semantic.ply, in total 5 files, is it correct? do I need .obj file?

**Comment by srama2512** [comment]
@rginjapan  Here is my dataset structure.
```
➜  gibson_semantic ls | head -n 10
Adairsville.glb
Adairsville.ids
Adairsville.navmesh
Adairsville.scn
Adairsville_semantic.ply
Airport.glb
Airport.ids
Airport.navmesh
Airport.scn
Airport_semantic.ply
```

**Comment by qymao** [comment]
I had the same problem, even follow your data structure. Could you please show us the detailed split of Gibson you used?

Number of available scenes: 0
===========> Extracting scene boundaries
0it [00:00, ?it/s]
===========> Extracting point-clouds
0it [00:00, ?it/s]
===========> Extracting semantic maps
0it [00:00, ?it/s]

**Comment by leyuan-sun** [comment]
<img width="186" alt="截屏2023-08-25 15 13 18" src="https://github.com/srama2512/PONI/assets/41459267/f731978e-3975-4a9a-bb2b-ebc2f78e1985">
Thanks for your reply, I have some scenes which do not contain all 5 formats such as Ackermanville only has two formats. Does it affect the results?

**Comment by srama2512** [comment]
@rginjapan - yes, that will affect the results. The semantic files are necessary to generate the objects in the semantic map. Can you please check the semantic maps for scenes with semantic files? They should contain the objects.

**Comment by Robot-zeg** [comment]
> Could you show the dataset folder structure? What are the files inside of gibson_semantic folder, for me, I have scene_name.glb scene_name.navmesh scene_name.ids scene_name.scn scene_name_semantic.ply, in total 5 files, is it correct? do I need .obj file?

@rginjapan I see you only have .ids .scn . _semantic .ply before. Could you tell me how to get .glb and .navmesh?

**Comment by leyuan-sun** [comment]
@Yuanze-wang I did not remember... I think they are downloaded from somewhere...

**Comment by NormanMises** [comment]
> I had the same problem, even follow your data structure. Could you please show us the detailed split of Gibson you used?
> 
> Number of available scenes: 0 ===========> Extracting scene boundaries 0it [00:00, ?it/s] ===========> Extracting point-clouds 0it [00:00, ?it/s] ===========> Extracting semantic maps 0it [00:00, ?it/s]

I have the same data structure, but still get this result. I remember [habitat-sim](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#gibson-and-3dscenegraph-datasets) says

> To use semantics, you will need to enable the semantic sensor.
> 
> Once you have downloaded the Gibson dataset and converted the semantic data, you should download [this SceneDatasetConfig file](http://dl.fbaipublicfiles.com/habitat/gibson/config_v1/gibson_semantic.scene_dataset_config.json) and place it in the root directory for the Gibson dataset (e.g. Habitat-Sim/data/scene_datasets/gibson/). This file should then be specified as [the scene dataset config in the SimulatorConfiguration structure](https://github.com/facebookresearch/habitat-sim/blob/main/examples/tutorials/nb_python/ReplicaCAD_quickstart.py#L145) like this example for the ReplicaCAD dataset.

But I don't quite understand how to do it specifically, so I skipped this step. Does this affect the result of the semantic annotation conversion? If so, please tell me how to do it, thank you!

**Comment by hldbalabala** [comment]
> <img alt="截屏2023-08-25 15 13 18" width="186" src="https://private-user-images.githubusercontent.com/41459267/263182274-f731978e-3975-4a9a-bb2b-ebc2f78e1985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY2OTQ5MTYsIm5iZiI6MTczNjY5NDYxNiwicGF0aCI6Ii80MTQ1OTI2Ny8yNjMxODIyNzQtZjczMTk3OGUtMzk3NS00YTlhLWJiMmItZWJjMmY3OGUxOTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEyVDE1MTAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ZDEzNDJkZTAyM2UwYTc3MDExYjRlMzQ3MDRiYzIyZTUzMjQ5M2ExMjNkOWE1ZGI2NjUxMmI3N2M3YmMzOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.93nYdH0B5pmwUtNorhw0fx0FrQGLcdwM5jMQne2nlLI"> Thanks for your reply, I have some scenes which do not contain all 5 formats such as Ackermanville only has two formats. Does it affect the results?

I'm having the same issue, please tell me how did you solve it. thank you!

**Comment by wbciscodeking** [comment]
@NormanMises Have you solved this problem?I met the same problem,if you have ideas for this work,could you please tell me how to do?My emal:3058874880@qq.com

**Comment by wbciscodeking** [comment]
@NormanMises Have you solved this problem?I met the same problem,if you have ideas for this work,could you please tell me how to do?My email:[3058874880@qq.com](mailto:3058874880@qq.com)

**Comment by wangweicheng945** [comment]
Hello,I have a question.I want to know how do you generated the semantic annotations for Gibson from 3DSceneGraph dataset.

**Comment by womeizhaol** [comment]
> ACTIVE_DATASET="gibson" python scripts/create_semantic_maps.py Number of available scenes: 0 ===========> Extracting scene boundaries 0it [00:00, ?it/s] ===========> Extracting point-clouds 0it [00:00, ?it/s] ===========> Extracting semantic maps 0it [00:00, ?it/s]
> 
> After I have generated the semantic annotations for Gibson from 3DSceneGraph dataset, I obtained the .ids and .scn files for each scene, and I put all of them in /gibson_semantic folder, then I would like to use create_semantic_maps.py to convert them to habitat format, but I got the aboved msgs. Could you plz take a look? Thanks!

May I ask if you have successfully downloaded it? Can we add a contact method to communicate?

**Comment by womeizhaol** [comment]
> @rginjapan - yes, that will affect the results. The semantic files are necessary to generate the objects in the semantic map. Can you please check the semantic maps for scenes with semantic files? They should contain the objects.

May I ask if you have successfully downloaded it? Can we add a contact method to communicate?

**Comment by wbciscodeking** [comment]
I think it's a problem of dataset ，I changed dataset and solved this problem.But I have forgo5ten some details

---Original---
From: ***@***.***&gt;
Date: Wed, Sep 3, 2025 19:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [srama2512/PONI] Convert the semantic annotations to habitatformat (Issue #14)


labixiaochao left a comment (srama2512/PONI#14)
  
@rginjapan - yes, that will affect the results. The semantic files are necessary to generate the objects in the semantic map. Can you please check the semantic maps for scenes with semantic files? They should contain the objects.
  
May I ask if you have successfully downloaded it? Can we add a contact method to communicate?
