### ISSUE TITLE
Deterministic Local Policy

### ISSUE THREAD

**Issue by KarelZhang** [srama2512/PONI#16]
great works!

could you please tell me where the code of "Deterministic Local Policy" is?

**Comment by srama2512** [comment]
@KarelZhang - It is integrated into the environment for Gibson (see [here](https://github.com/srama2512/PONI/blob/30682c2bdcd820eec8f72043b2579eb045d547bf/semexp/envs/habitat/sem_exp.py#L135)). It is defined explicitly for MP3D (see [here](https://github.com/srama2512/PONI/blob/30682c2bdcd820eec8f72043b2579eb045d547bf/hlab/global_agent.py#L381-L383)).
