### ISSUE TITLE
The calculation of area_pf

### ISSUE THREAD

**Issue by leyuan-sun** [srama2512/PONI#20]
Could you plz explain more about "we first group the unexplored free-space cells into con- nected components C = {c1, · · · , cn} using OpenCV , A component c is associated with frontier f only if at least one pixel in c is an 8-connected neighbor [58] of some pixel in f " , and where is the implementation of area_pf calculation of aboved sentence? Thanks ahead!!

**Comment by srama2512** [comment]
You can find details about the area pf calculation [here](https://github.com/srama2512/PONI/blob/30682c2bdcd820eec8f72043b2579eb045d547bf/poni/dataset.py#L795-L845).

**Comment by leyuan-sun** [comment]
I see, thanks! 
Btw, I do not clearly understand this "Since the geometrically-calculated map frontiers can be noisy during navigation, we retain the predictions from the unexplored locations, providing the model some flexibility in deciding the frontier boundaries. ", could you plz explain more?

**Comment by srama2512** [comment]
Good question. Analytically calculating frontiers resulted in some noisy frontiers. So we let the model decide what the frontier boundaries are amongst the unexplored cells (instead of analytically picking only the frontier boundaries from the unexplored areas).

**Comment by yuanxuanS** [comment]
Does it mean that model predicts potentials on all pixels? 
But loss is not on no-frontier region, how can it avoid model from predict potential on no-frontiers?
