### ISSUE TITLE
Question about object categories

### ISSUE THREAD

**Issue by YYDS-cc** [srama2512/PONI#22]
Nice work！

The potential function network πpf uses the goal object category (o) to predict the object potential functions. What form of object category inputted into the network? One-hot vector or others?
Only the names of the object categories are presented in the literature [6], and the specific form in the dataset is not described.

Plz give me some advice.

**Comment by srama2512** [comment]
Hi @YYDS-cc,

Thanks for your interest in our work. We do not input the object category explicitly. Instead, the model predicts potential functions for all defined object categories simultaneously (see [here](https://github.com/srama2512/PONI/blob/30682c2bdcd820eec8f72043b2579eb045d547bf/poni/model.py#L287-L291)) and we pick the potential-function corresponding to the goal category during navigation (see [here](https://github.com/srama2512/PONI/blob/30682c2bdcd820eec8f72043b2579eb045d547bf/semexp/model_pf.py#L247)).

**Comment by YYDS-cc** [comment]
Thank you for your reply！
