### ISSUE TITLE
How the RL policy used during inference?

### ISSUE THREAD

**Issue by leyuan-sun** [srama2512/PONI#23]
I study your code and find out that the RL-Policy class only be used in inference, in the training, your pipline is a supervised learning framework to predict the long-term goal position, am I correct? Thanks!

**Comment by srama2512** [comment]
@rginjapan - During training, we train the potential function network to infer area and object PFs (not long-term goals). We do not use any RL or interactive simulation during training. Sec. 3.6 in [our paper](https://arxiv.org/pdf/2201.10029.pdf) explains how supervised training works. 

During inference, we use the potential function network to infer area + object PFs, linearly combine them to obtain a joint PF and sample the maximum location of the joint potential as the long-term goal. See Sec. 3.3 in our paper in this regard.

**Comment by leyuan-sun** [comment]
Thanks for your reply, so there is no RL in your pipeline, only supervised learning for PF, am I correct?

**Comment by srama2512** [comment]
Yes, that is correct.
