### ISSUE TITLE
Question about generated semantic maps

### ISSUE THREAD

**Issue by ZhengLeon** [srama2512/PONI#25]
Hi @srama2512,
Thanks for your great work.
After generating the semantic maps like this:
[1-LXt-Fkjw3q-L-1.png](https://postimg.cc/YhtH25Nc)
I can't successfully calculate the fmm_dists.
May I ask why there are no semantic annotations in my semantic maps? Thanks a lot.

**Comment by srama2512** [comment]
@ZhengLeon  - thanks for your interest in our work. What procedure did you use to generate the map? Can you provide the steps to reproduce?

**Comment by ZhengLeon** [comment]
@srama2512 , thanks for your kind reply.
I used the codes as follow to convert the raw MP3D scenes to GLB:
```
data_path = "/mnt/PONI/data/scene_datasets/mp3d_uncompressed/v1/scans"
first_directory = os.listdir(data_path)

for second_directory in first_directory:
  mesh_directory = os.path.join(data_path, second_directory, 'matterport_mesh')
  scene_directory = os.listdir(mesh_directory)
  for scene in scene_directory:
    obj_file_path = os.path.join(mesh_directory, scene, scene+'.obj')
    glb_file_path = os.path.join(mesh_directory, scene, second_directory+'.glb')
    if os.path.exists(obj_file_path):
      print(obj_file_path)
      scene = trimesh.load(obj_file_path)
      scene.export(glb_file_path)
```
Then, I use the below script to extract MP3D semantic maps:
`ACTIVE_DATASET="mp3d" python scripts/create_semantic_maps.py`

And the generated GT_info is attached here:
[semmap_GT_info.json.zip](https://github.com/srama2512/PONI/files/12328535/semmap_GT_info.json.zip)

Thanks.

**Comment by srama2512** [comment]
@ZhengLeon  - After converting, did you ensure that the semantic ply files are also present in the scene directory? This is my current file structure
```
> cd <PATH TO MATTERPORT DIR>/17DRP5sb8fy/
> ls
17DRP5sb8fy.glb  17DRP5sb8fy.house  17DRP5sb8fy.navmesh  17DRP5sb8fy_semantic.ply
```

**Comment by ZhengLeon** [comment]
Hi, @srama2512
Yes, there exists semantic ply files. But the .navmesh and .house files are missed. May I ask if they are initiated in the original dataset? Thanks!

**Comment by srama2512** [comment]
Hi @ZhengLeon,

You can get the full dataset by following the instructions from [here](https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#matterport3d-mp3d-dataset). Note that the `.glb` files you get through this download will be basis compressed. You have to use instead the `.glb` files generated from `.obj`.

**Comment by ZhengLeon** [comment]
@srama2512 , thanks for your guidance.
Now I can successfully generate the semantic maps.
However, I get only 108 train / 21 val maps from `precompute_fmm_dists.py`, which is different from the paper "153 train / 21 val".
Is something wrong with my split?

**Comment by srama2512** [comment]
Great! No, there's nothing wrong. The 153 number in the paper is a typo since it includes train + test. Please see [this](https://github.com/srama2512/PONI/issues/11#issuecomment-1365608790) issue comment for more details.

**Comment by ZhengLeon** [comment]
@srama2512, thanks for helping.
I will close this issue now.
