### ISSUE TITLE
goal category

### ISSUE THREAD

**Issue by leyuan-sun** [srama2512/PONI#26]
could I ask a simple question? where to define the goal category, I know there are 6 goals in Gibson dataset.

**Comment by srama2512** [comment]
> could I ask a simple question? where to define the goal category, I know there are 6 goals in Gibson dataset.

Hi @rginjapan. What exactly do you mean? Do you want to know where the categories are defined, or how to change them?

**Comment by leyuan-sun** [comment]
Could you plz explain both?

**Comment by srama2512** [comment]
@rginjapan  - [this](https://github.com/srama2512/PONI/blob/30682c2bdcd820eec8f72043b2579eb045d547bf/poni/constants.py#L116-L161) defines the categories we use for each dataset. You should be able to modify this for your use case.

**Comment by leyuan-sun** [comment]
Thanks for your reply, where define the goal category?

**Comment by srama2512** [comment]
We assume that the first N categories (see [Gibson](https://github.com/srama2512/PONI/blob/30682c2bdcd820eec8f72043b2579eb045d547bf/poni/constants.py#L120-L125) and [MP3D](https://github.com/srama2512/PONI/blob/30682c2bdcd820eec8f72043b2579eb045d547bf/poni/constants.py#L139-L159)) are goal categories.
