### ISSUE TITLE
Questions about Nav settings; Do you use Chaplot's OGN?

### ISSUE THREAD

**Issue by soyeonm** [srama2512/PONI#4]
Hello,
I know that someone else has already opened an issue here(https://github.com/srama2512/PONI/issues/2); I understand that releasing the whole code can take up much energy and time.

If you using the infrastructure in Chaplot's OGN(https://github.com/devendrachaplot/Object-Goal-Navigation), I wonder if you could share some settings for plugging in PONI to OGN.

1. Do you use the infrastructure of OGN?
2. If so, for the "input" of PONI, do you use the "local map", or "full map"? If you use the "full map" as your input, then how do you map back from the argmax of the potential (the selected goal point) back to the local map (since the local map is used for fmm planning)?
3. If you use OGN, what were your sizes of local map/ full map?

Thanks!

**Comment by srama2512** [comment]
@soyeonm  - Thank you for your patience. The complete ObjectNav code has been released. I hope you find it answers all your questions. Feel free to re-open the issue / create a new issue otherwise.
