### ISSUE TITLE
TensorFlow1.13.1

### ISSUE THREAD

**Issue by Routine113** [srama2512/PONI#5]
The request in giuhub is Python:3.8.5 , and TensorFlow : 1.13.1 .
But installing TensorFlow1.13.1 requires Python version 3.8 or below
'''
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - tensorflow==1.13.1 -> python[version='>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8.5

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
'''

**Comment by Routine113** [comment]
OK，I have solved this problem.I reconfigured the environment and used Python 3.7 .But I don't know if it will affect the follow-up work

**Comment by srama2512** [comment]
@Routine113  - The code doesn't use tensorflow at all. I think this issue comes from the habitat-lab baselines installation which requires tensorflow 1.13.1. I would suggest you comment out the tensorflow requirement and follow the installation process.
